#!/bin/bash

sudo apt-get update
sudo apt-get install -y apt-transport-https

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo touch /etc/apt/sources.list.d/kubernetes.list
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl

echo "*  *  *  *  *"
echo
kubectl api-versions
echo
echo "*  *  *  *  *"
echo
echo "Run command to create kubernetes cluster on GCP"
echo "gcloud container clusters create [CLUSTER_NAME]"
echo
echo "*  *  *  *  *"


#  # add input check if user wants to install minicube
# curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64
# chmod +x minikube && sudo mv minikube /usr/local/bin/
#  # and ask if they wanna run it
# minikube start
