#!/bin/bash

sudo apt-get update
sudo apt-get install -y apt-transport-https

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo touch /etc/apt/sources.list.d/kubernetes.list
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubectl

while true; do
  echo
  echo "Minikube makes it easy to run Kubernetes locally, running a single-node cluster on your machine."
  echo "Good for trying out Kubernetes or not being overwhelmed by a big cluster network"
  echo "*  *  *  *  *"
  echo
  read -r -p "Install Minikube? " yn
  case $yn in
    [Yy][Ee][sS]|[yY]* )
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64
      chmod +x minikube && sudo mv minikube /usr/local/bin/
	    echo
      minikube start
      echo
      break;;
    [Nn][Oo]|[nN]* )
	    exit;;
    * ) echo "Pick a valid input ...";;
  esac
done

echo "*  *  *  *  *"
echo
kubectl api-versions
echo
echo "*  *  *  *  *"
echo
echo "Run command to create kubernetes cluster on GCP"
echo "gcloud container clusters create [CLUSTER_NAME]"
echo
echo "*  *  *  *  *"


#  # add input check if user wants to install minicube
# curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64
# chmod +x minikube && sudo mv minikube /usr/local/bin/
#  # and ask if they wanna run it
# minikube start
